
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'UiAlert': typeof import("../../app/components/ui/UiAlert.vue").default
  'UiAvatar': typeof import("../../app/components/ui/UiAvatar.vue").default
  'UiBadge': typeof import("../../app/components/ui/UiBadge.vue").default
  'UiBreadcrumb': typeof import("../../app/components/ui/UiBreadcrumb.vue").default
  'UiButton': typeof import("../../app/components/ui/UiButton.vue").default
  'UiCard': typeof import("../../app/components/ui/UiCard.vue").default
  'UiCheckbox': typeof import("../../app/components/ui/UiCheckbox.vue").default
  'UiConfirmDialog': typeof import("../../app/components/ui/UiConfirmDialog.vue").default
  'UiDrawer': typeof import("../../app/components/ui/UiDrawer.vue").default
  'UiDropdown': typeof import("../../app/components/ui/UiDropdown.vue").default
  'UiDropdownItem': typeof import("../../app/components/ui/UiDropdownItem.vue").default
  'UiEmptyState': typeof import("../../app/components/ui/UiEmptyState.vue").default
  'UiInput': typeof import("../../app/components/ui/UiInput.vue").default
  'UiLoadingBar': typeof import("../../app/components/ui/UiLoadingBar.vue").default
  'UiModal': typeof import("../../app/components/ui/UiModal.vue").default
  'UiOfflineIndicator': typeof import("../../app/components/ui/UiOfflineIndicator.vue").default
  'UiPagination': typeof import("../../app/components/ui/UiPagination.vue").default
  'UiProgress': typeof import("../../app/components/ui/UiProgress.vue").default
  'UiRadio': typeof import("../../app/components/ui/UiRadio.vue").default
  'UiSelect': typeof import("../../app/components/ui/UiSelect.vue").default
  'UiSkeleton': typeof import("../../app/components/ui/UiSkeleton.vue").default
  'UiSpinner': typeof import("../../app/components/ui/UiSpinner.vue").default
  'UiSwitch': typeof import("../../app/components/ui/UiSwitch.vue").default
  'UiTabs': typeof import("../../app/components/ui/UiTabs.vue").default
  'UiTextarea': typeof import("../../app/components/ui/UiTextarea.vue").default
  'UiToast': typeof import("../../app/components/ui/UiToast.vue").default
  'UiTooltip': typeof import("../../app/components/ui/UiTooltip.vue").default
  'FormCheckbox': typeof import("../../app/components/form/FormCheckbox.vue").default
  'FormDatePicker': typeof import("../../app/components/form/FormDatePicker.vue").default
  'FormField': typeof import("../../app/components/form/FormField.vue").default
  'FormFileUpload': typeof import("../../app/components/form/FormFileUpload.vue").default
  'FormInput': typeof import("../../app/components/form/FormInput.vue").default
  'FormSelect': typeof import("../../app/components/form/FormSelect.vue").default
  'FormSwitch': typeof import("../../app/components/form/FormSwitch.vue").default
  'FormTextarea': typeof import("../../app/components/form/FormTextarea.vue").default
  'LanguageSwitcher': typeof import("../../app/components/layout/LanguageSwitcher.vue").default
  'PageHeader': typeof import("../../app/components/layout/PageHeader.vue").default
  'SidebarItem': typeof import("../../app/components/layout/SidebarItem.vue").default
  'TheHeader': typeof import("../../app/components/layout/TheHeader.vue").default
  'TheSidebar': typeof import("../../app/components/layout/TheSidebar.vue").default
  'ThemeToggle': typeof import("../../app/components/layout/ThemeToggle.vue").default
  'UserMenu': typeof import("../../app/components/layout/UserMenu.vue").default
  'DataTable': typeof import("../../app/components/data/DataTable.vue").default
  'DataTableActions': typeof import("../../app/components/data/DataTableActions.vue").default
  'AreaChart': typeof import("../../app/components/charts/AreaChart.vue").default
  'BarChart': typeof import("../../app/components/charts/BarChart.vue").default
  'DonutChart': typeof import("../../app/components/charts/DonutChart.vue").default
  'LineChart': typeof import("../../app/components/charts/LineChart.vue").default
  'PieChart': typeof import("../../app/components/charts/PieChart.vue").default
  'AIProviderStatus': typeof import("../../app/components/dashboard/AIProviderStatus.vue").default
  'LowStockAlerts': typeof import("../../app/components/dashboard/LowStockAlerts.vue").default
  'RecentConversations': typeof import("../../app/components/dashboard/RecentConversations.vue").default
  'RecentOrders': typeof import("../../app/components/dashboard/RecentOrders.vue").default
  'StatsCard': typeof import("../../app/components/dashboard/StatsCard.vue").default
  'SystemHealth': typeof import("../../app/components/dashboard/SystemHealth.vue").default
  'ConversationChat': typeof import("../../app/components/conversations/ConversationChat.vue").default
  'ConversationFilters': typeof import("../../app/components/conversations/ConversationFilters.vue").default
  'ConversationList': typeof import("../../app/components/conversations/ConversationList.vue").default
  'CustomerSidebar': typeof import("../../app/components/conversations/CustomerSidebar.vue").default
  'MessageBubble': typeof import("../../app/components/conversations/MessageBubble.vue").default
  'OrderFilters': typeof import("../../app/components/orders/OrderFilters.vue").default
  'OrderItemsTable': typeof import("../../app/components/orders/OrderItemsTable.vue").default
  'OrderList': typeof import("../../app/components/orders/OrderList.vue").default
  'OrderStatusBadge': typeof import("../../app/components/orders/OrderStatusBadge.vue").default
  'OrderSummary': typeof import("../../app/components/orders/OrderSummary.vue").default
  'OrderTimeline': typeof import("../../app/components/orders/OrderTimeline.vue").default
  'ProductCard': typeof import("../../app/components/products/ProductCard.vue").default
  'ProductFilters': typeof import("../../app/components/products/ProductFilters.vue").default
  'ProductForm': typeof import("../../app/components/products/ProductForm.vue").default
  'ProductImages': typeof import("../../app/components/products/ProductImages.vue").default
  'ProductList': typeof import("../../app/components/products/ProductList.vue").default
  'ProductVariants': typeof import("../../app/components/products/ProductVariants.vue").default
  'StockBadge': typeof import("../../app/components/products/StockBadge.vue").default
  'CustomerConversations': typeof import("../../app/components/customers/CustomerConversations.vue").default
  'CustomerFilters': typeof import("../../app/components/customers/CustomerFilters.vue").default
  'CustomerList': typeof import("../../app/components/customers/CustomerList.vue").default
  'CustomerOrders': typeof import("../../app/components/customers/CustomerOrders.vue").default
  'CustomerStats': typeof import("../../app/components/customers/CustomerStats.vue").default
  'KnowledgeForm': typeof import("../../app/components/settings/KnowledgeForm.vue").default
  'KnowledgeList': typeof import("../../app/components/settings/KnowledgeList.vue").default
  'PatternSection': typeof import("../../app/components/settings/PatternSection.vue").default
  'SettingsBot': typeof import("../../app/components/settings/SettingsBot.vue").default
  'SettingsCurrency': typeof import("../../app/components/settings/SettingsCurrency.vue").default
  'SettingsNotifications': typeof import("../../app/components/settings/SettingsNotifications.vue").default
  'SettingsShipping': typeof import("../../app/components/settings/SettingsShipping.vue").default
  'SettingsStoreInfo': typeof import("../../app/components/settings/SettingsStoreInfo.vue").default
  'TemplateForm': typeof import("../../app/components/settings/TemplateForm.vue").default
  'TemplatesList': typeof import("../../app/components/settings/TemplatesList.vue").default
  'GlobalConfirmDialog': typeof import("../../app/components/GlobalConfirmDialog.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyUiAlert': LazyComponent<typeof import("../../app/components/ui/UiAlert.vue").default>
  'LazyUiAvatar': LazyComponent<typeof import("../../app/components/ui/UiAvatar.vue").default>
  'LazyUiBadge': LazyComponent<typeof import("../../app/components/ui/UiBadge.vue").default>
  'LazyUiBreadcrumb': LazyComponent<typeof import("../../app/components/ui/UiBreadcrumb.vue").default>
  'LazyUiButton': LazyComponent<typeof import("../../app/components/ui/UiButton.vue").default>
  'LazyUiCard': LazyComponent<typeof import("../../app/components/ui/UiCard.vue").default>
  'LazyUiCheckbox': LazyComponent<typeof import("../../app/components/ui/UiCheckbox.vue").default>
  'LazyUiConfirmDialog': LazyComponent<typeof import("../../app/components/ui/UiConfirmDialog.vue").default>
  'LazyUiDrawer': LazyComponent<typeof import("../../app/components/ui/UiDrawer.vue").default>
  'LazyUiDropdown': LazyComponent<typeof import("../../app/components/ui/UiDropdown.vue").default>
  'LazyUiDropdownItem': LazyComponent<typeof import("../../app/components/ui/UiDropdownItem.vue").default>
  'LazyUiEmptyState': LazyComponent<typeof import("../../app/components/ui/UiEmptyState.vue").default>
  'LazyUiInput': LazyComponent<typeof import("../../app/components/ui/UiInput.vue").default>
  'LazyUiLoadingBar': LazyComponent<typeof import("../../app/components/ui/UiLoadingBar.vue").default>
  'LazyUiModal': LazyComponent<typeof import("../../app/components/ui/UiModal.vue").default>
  'LazyUiOfflineIndicator': LazyComponent<typeof import("../../app/components/ui/UiOfflineIndicator.vue").default>
  'LazyUiPagination': LazyComponent<typeof import("../../app/components/ui/UiPagination.vue").default>
  'LazyUiProgress': LazyComponent<typeof import("../../app/components/ui/UiProgress.vue").default>
  'LazyUiRadio': LazyComponent<typeof import("../../app/components/ui/UiRadio.vue").default>
  'LazyUiSelect': LazyComponent<typeof import("../../app/components/ui/UiSelect.vue").default>
  'LazyUiSkeleton': LazyComponent<typeof import("../../app/components/ui/UiSkeleton.vue").default>
  'LazyUiSpinner': LazyComponent<typeof import("../../app/components/ui/UiSpinner.vue").default>
  'LazyUiSwitch': LazyComponent<typeof import("../../app/components/ui/UiSwitch.vue").default>
  'LazyUiTabs': LazyComponent<typeof import("../../app/components/ui/UiTabs.vue").default>
  'LazyUiTextarea': LazyComponent<typeof import("../../app/components/ui/UiTextarea.vue").default>
  'LazyUiToast': LazyComponent<typeof import("../../app/components/ui/UiToast.vue").default>
  'LazyUiTooltip': LazyComponent<typeof import("../../app/components/ui/UiTooltip.vue").default>
  'LazyFormCheckbox': LazyComponent<typeof import("../../app/components/form/FormCheckbox.vue").default>
  'LazyFormDatePicker': LazyComponent<typeof import("../../app/components/form/FormDatePicker.vue").default>
  'LazyFormField': LazyComponent<typeof import("../../app/components/form/FormField.vue").default>
  'LazyFormFileUpload': LazyComponent<typeof import("../../app/components/form/FormFileUpload.vue").default>
  'LazyFormInput': LazyComponent<typeof import("../../app/components/form/FormInput.vue").default>
  'LazyFormSelect': LazyComponent<typeof import("../../app/components/form/FormSelect.vue").default>
  'LazyFormSwitch': LazyComponent<typeof import("../../app/components/form/FormSwitch.vue").default>
  'LazyFormTextarea': LazyComponent<typeof import("../../app/components/form/FormTextarea.vue").default>
  'LazyLanguageSwitcher': LazyComponent<typeof import("../../app/components/layout/LanguageSwitcher.vue").default>
  'LazyPageHeader': LazyComponent<typeof import("../../app/components/layout/PageHeader.vue").default>
  'LazySidebarItem': LazyComponent<typeof import("../../app/components/layout/SidebarItem.vue").default>
  'LazyTheHeader': LazyComponent<typeof import("../../app/components/layout/TheHeader.vue").default>
  'LazyTheSidebar': LazyComponent<typeof import("../../app/components/layout/TheSidebar.vue").default>
  'LazyThemeToggle': LazyComponent<typeof import("../../app/components/layout/ThemeToggle.vue").default>
  'LazyUserMenu': LazyComponent<typeof import("../../app/components/layout/UserMenu.vue").default>
  'LazyDataTable': LazyComponent<typeof import("../../app/components/data/DataTable.vue").default>
  'LazyDataTableActions': LazyComponent<typeof import("../../app/components/data/DataTableActions.vue").default>
  'LazyAreaChart': LazyComponent<typeof import("../../app/components/charts/AreaChart.vue").default>
  'LazyBarChart': LazyComponent<typeof import("../../app/components/charts/BarChart.vue").default>
  'LazyDonutChart': LazyComponent<typeof import("../../app/components/charts/DonutChart.vue").default>
  'LazyLineChart': LazyComponent<typeof import("../../app/components/charts/LineChart.vue").default>
  'LazyPieChart': LazyComponent<typeof import("../../app/components/charts/PieChart.vue").default>
  'LazyAIProviderStatus': LazyComponent<typeof import("../../app/components/dashboard/AIProviderStatus.vue").default>
  'LazyLowStockAlerts': LazyComponent<typeof import("../../app/components/dashboard/LowStockAlerts.vue").default>
  'LazyRecentConversations': LazyComponent<typeof import("../../app/components/dashboard/RecentConversations.vue").default>
  'LazyRecentOrders': LazyComponent<typeof import("../../app/components/dashboard/RecentOrders.vue").default>
  'LazyStatsCard': LazyComponent<typeof import("../../app/components/dashboard/StatsCard.vue").default>
  'LazySystemHealth': LazyComponent<typeof import("../../app/components/dashboard/SystemHealth.vue").default>
  'LazyConversationChat': LazyComponent<typeof import("../../app/components/conversations/ConversationChat.vue").default>
  'LazyConversationFilters': LazyComponent<typeof import("../../app/components/conversations/ConversationFilters.vue").default>
  'LazyConversationList': LazyComponent<typeof import("../../app/components/conversations/ConversationList.vue").default>
  'LazyCustomerSidebar': LazyComponent<typeof import("../../app/components/conversations/CustomerSidebar.vue").default>
  'LazyMessageBubble': LazyComponent<typeof import("../../app/components/conversations/MessageBubble.vue").default>
  'LazyOrderFilters': LazyComponent<typeof import("../../app/components/orders/OrderFilters.vue").default>
  'LazyOrderItemsTable': LazyComponent<typeof import("../../app/components/orders/OrderItemsTable.vue").default>
  'LazyOrderList': LazyComponent<typeof import("../../app/components/orders/OrderList.vue").default>
  'LazyOrderStatusBadge': LazyComponent<typeof import("../../app/components/orders/OrderStatusBadge.vue").default>
  'LazyOrderSummary': LazyComponent<typeof import("../../app/components/orders/OrderSummary.vue").default>
  'LazyOrderTimeline': LazyComponent<typeof import("../../app/components/orders/OrderTimeline.vue").default>
  'LazyProductCard': LazyComponent<typeof import("../../app/components/products/ProductCard.vue").default>
  'LazyProductFilters': LazyComponent<typeof import("../../app/components/products/ProductFilters.vue").default>
  'LazyProductForm': LazyComponent<typeof import("../../app/components/products/ProductForm.vue").default>
  'LazyProductImages': LazyComponent<typeof import("../../app/components/products/ProductImages.vue").default>
  'LazyProductList': LazyComponent<typeof import("../../app/components/products/ProductList.vue").default>
  'LazyProductVariants': LazyComponent<typeof import("../../app/components/products/ProductVariants.vue").default>
  'LazyStockBadge': LazyComponent<typeof import("../../app/components/products/StockBadge.vue").default>
  'LazyCustomerConversations': LazyComponent<typeof import("../../app/components/customers/CustomerConversations.vue").default>
  'LazyCustomerFilters': LazyComponent<typeof import("../../app/components/customers/CustomerFilters.vue").default>
  'LazyCustomerList': LazyComponent<typeof import("../../app/components/customers/CustomerList.vue").default>
  'LazyCustomerOrders': LazyComponent<typeof import("../../app/components/customers/CustomerOrders.vue").default>
  'LazyCustomerStats': LazyComponent<typeof import("../../app/components/customers/CustomerStats.vue").default>
  'LazyKnowledgeForm': LazyComponent<typeof import("../../app/components/settings/KnowledgeForm.vue").default>
  'LazyKnowledgeList': LazyComponent<typeof import("../../app/components/settings/KnowledgeList.vue").default>
  'LazyPatternSection': LazyComponent<typeof import("../../app/components/settings/PatternSection.vue").default>
  'LazySettingsBot': LazyComponent<typeof import("../../app/components/settings/SettingsBot.vue").default>
  'LazySettingsCurrency': LazyComponent<typeof import("../../app/components/settings/SettingsCurrency.vue").default>
  'LazySettingsNotifications': LazyComponent<typeof import("../../app/components/settings/SettingsNotifications.vue").default>
  'LazySettingsShipping': LazyComponent<typeof import("../../app/components/settings/SettingsShipping.vue").default>
  'LazySettingsStoreInfo': LazyComponent<typeof import("../../app/components/settings/SettingsStoreInfo.vue").default>
  'LazyTemplateForm': LazyComponent<typeof import("../../app/components/settings/TemplateForm.vue").default>
  'LazyTemplatesList': LazyComponent<typeof import("../../app/components/settings/TemplatesList.vue").default>
  'LazyGlobalConfirmDialog': LazyComponent<typeof import("../../app/components/GlobalConfirmDialog.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
