
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const UiAlert: typeof import("../app/components/ui/UiAlert.vue").default
export const UiAvatar: typeof import("../app/components/ui/UiAvatar.vue").default
export const UiBadge: typeof import("../app/components/ui/UiBadge.vue").default
export const UiBreadcrumb: typeof import("../app/components/ui/UiBreadcrumb.vue").default
export const UiButton: typeof import("../app/components/ui/UiButton.vue").default
export const UiCard: typeof import("../app/components/ui/UiCard.vue").default
export const UiCheckbox: typeof import("../app/components/ui/UiCheckbox.vue").default
export const UiConfirmDialog: typeof import("../app/components/ui/UiConfirmDialog.vue").default
export const UiDrawer: typeof import("../app/components/ui/UiDrawer.vue").default
export const UiDropdown: typeof import("../app/components/ui/UiDropdown.vue").default
export const UiDropdownItem: typeof import("../app/components/ui/UiDropdownItem.vue").default
export const UiEmptyState: typeof import("../app/components/ui/UiEmptyState.vue").default
export const UiInput: typeof import("../app/components/ui/UiInput.vue").default
export const UiLoadingBar: typeof import("../app/components/ui/UiLoadingBar.vue").default
export const UiModal: typeof import("../app/components/ui/UiModal.vue").default
export const UiOfflineIndicator: typeof import("../app/components/ui/UiOfflineIndicator.vue").default
export const UiPagination: typeof import("../app/components/ui/UiPagination.vue").default
export const UiProgress: typeof import("../app/components/ui/UiProgress.vue").default
export const UiRadio: typeof import("../app/components/ui/UiRadio.vue").default
export const UiSelect: typeof import("../app/components/ui/UiSelect.vue").default
export const UiSkeleton: typeof import("../app/components/ui/UiSkeleton.vue").default
export const UiSpinner: typeof import("../app/components/ui/UiSpinner.vue").default
export const UiSwitch: typeof import("../app/components/ui/UiSwitch.vue").default
export const UiTabs: typeof import("../app/components/ui/UiTabs.vue").default
export const UiTextarea: typeof import("../app/components/ui/UiTextarea.vue").default
export const UiToast: typeof import("../app/components/ui/UiToast.vue").default
export const UiTooltip: typeof import("../app/components/ui/UiTooltip.vue").default
export const FormCheckbox: typeof import("../app/components/form/FormCheckbox.vue").default
export const FormDatePicker: typeof import("../app/components/form/FormDatePicker.vue").default
export const FormField: typeof import("../app/components/form/FormField.vue").default
export const FormFileUpload: typeof import("../app/components/form/FormFileUpload.vue").default
export const FormInput: typeof import("../app/components/form/FormInput.vue").default
export const FormSelect: typeof import("../app/components/form/FormSelect.vue").default
export const FormSwitch: typeof import("../app/components/form/FormSwitch.vue").default
export const FormTextarea: typeof import("../app/components/form/FormTextarea.vue").default
export const LanguageSwitcher: typeof import("../app/components/layout/LanguageSwitcher.vue").default
export const PageHeader: typeof import("../app/components/layout/PageHeader.vue").default
export const SidebarItem: typeof import("../app/components/layout/SidebarItem.vue").default
export const TheHeader: typeof import("../app/components/layout/TheHeader.vue").default
export const TheSidebar: typeof import("../app/components/layout/TheSidebar.vue").default
export const ThemeToggle: typeof import("../app/components/layout/ThemeToggle.vue").default
export const UserMenu: typeof import("../app/components/layout/UserMenu.vue").default
export const DataTable: typeof import("../app/components/data/DataTable.vue").default
export const DataTableActions: typeof import("../app/components/data/DataTableActions.vue").default
export const AreaChart: typeof import("../app/components/charts/AreaChart.vue").default
export const BarChart: typeof import("../app/components/charts/BarChart.vue").default
export const DonutChart: typeof import("../app/components/charts/DonutChart.vue").default
export const LineChart: typeof import("../app/components/charts/LineChart.vue").default
export const PieChart: typeof import("../app/components/charts/PieChart.vue").default
export const AIProviderStatus: typeof import("../app/components/dashboard/AIProviderStatus.vue").default
export const LowStockAlerts: typeof import("../app/components/dashboard/LowStockAlerts.vue").default
export const RecentConversations: typeof import("../app/components/dashboard/RecentConversations.vue").default
export const RecentOrders: typeof import("../app/components/dashboard/RecentOrders.vue").default
export const StatsCard: typeof import("../app/components/dashboard/StatsCard.vue").default
export const SystemHealth: typeof import("../app/components/dashboard/SystemHealth.vue").default
export const ConversationChat: typeof import("../app/components/conversations/ConversationChat.vue").default
export const ConversationFilters: typeof import("../app/components/conversations/ConversationFilters.vue").default
export const ConversationList: typeof import("../app/components/conversations/ConversationList.vue").default
export const CustomerSidebar: typeof import("../app/components/conversations/CustomerSidebar.vue").default
export const MessageBubble: typeof import("../app/components/conversations/MessageBubble.vue").default
export const OrderFilters: typeof import("../app/components/orders/OrderFilters.vue").default
export const OrderItemsTable: typeof import("../app/components/orders/OrderItemsTable.vue").default
export const OrderList: typeof import("../app/components/orders/OrderList.vue").default
export const OrderStatusBadge: typeof import("../app/components/orders/OrderStatusBadge.vue").default
export const OrderSummary: typeof import("../app/components/orders/OrderSummary.vue").default
export const OrderTimeline: typeof import("../app/components/orders/OrderTimeline.vue").default
export const ProductCard: typeof import("../app/components/products/ProductCard.vue").default
export const ProductFilters: typeof import("../app/components/products/ProductFilters.vue").default
export const ProductForm: typeof import("../app/components/products/ProductForm.vue").default
export const ProductImages: typeof import("../app/components/products/ProductImages.vue").default
export const ProductList: typeof import("../app/components/products/ProductList.vue").default
export const ProductVariants: typeof import("../app/components/products/ProductVariants.vue").default
export const StockBadge: typeof import("../app/components/products/StockBadge.vue").default
export const CustomerConversations: typeof import("../app/components/customers/CustomerConversations.vue").default
export const CustomerFilters: typeof import("../app/components/customers/CustomerFilters.vue").default
export const CustomerList: typeof import("../app/components/customers/CustomerList.vue").default
export const CustomerOrders: typeof import("../app/components/customers/CustomerOrders.vue").default
export const CustomerStats: typeof import("../app/components/customers/CustomerStats.vue").default
export const KnowledgeForm: typeof import("../app/components/settings/KnowledgeForm.vue").default
export const KnowledgeList: typeof import("../app/components/settings/KnowledgeList.vue").default
export const PatternSection: typeof import("../app/components/settings/PatternSection.vue").default
export const SettingsBot: typeof import("../app/components/settings/SettingsBot.vue").default
export const SettingsCurrency: typeof import("../app/components/settings/SettingsCurrency.vue").default
export const SettingsNotifications: typeof import("../app/components/settings/SettingsNotifications.vue").default
export const SettingsShipping: typeof import("../app/components/settings/SettingsShipping.vue").default
export const SettingsStoreInfo: typeof import("../app/components/settings/SettingsStoreInfo.vue").default
export const TemplateForm: typeof import("../app/components/settings/TemplateForm.vue").default
export const TemplatesList: typeof import("../app/components/settings/TemplatesList.vue").default
export const GlobalConfirmDialog: typeof import("../app/components/GlobalConfirmDialog.vue").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyUiAlert: LazyComponent<typeof import("../app/components/ui/UiAlert.vue").default>
export const LazyUiAvatar: LazyComponent<typeof import("../app/components/ui/UiAvatar.vue").default>
export const LazyUiBadge: LazyComponent<typeof import("../app/components/ui/UiBadge.vue").default>
export const LazyUiBreadcrumb: LazyComponent<typeof import("../app/components/ui/UiBreadcrumb.vue").default>
export const LazyUiButton: LazyComponent<typeof import("../app/components/ui/UiButton.vue").default>
export const LazyUiCard: LazyComponent<typeof import("../app/components/ui/UiCard.vue").default>
export const LazyUiCheckbox: LazyComponent<typeof import("../app/components/ui/UiCheckbox.vue").default>
export const LazyUiConfirmDialog: LazyComponent<typeof import("../app/components/ui/UiConfirmDialog.vue").default>
export const LazyUiDrawer: LazyComponent<typeof import("../app/components/ui/UiDrawer.vue").default>
export const LazyUiDropdown: LazyComponent<typeof import("../app/components/ui/UiDropdown.vue").default>
export const LazyUiDropdownItem: LazyComponent<typeof import("../app/components/ui/UiDropdownItem.vue").default>
export const LazyUiEmptyState: LazyComponent<typeof import("../app/components/ui/UiEmptyState.vue").default>
export const LazyUiInput: LazyComponent<typeof import("../app/components/ui/UiInput.vue").default>
export const LazyUiLoadingBar: LazyComponent<typeof import("../app/components/ui/UiLoadingBar.vue").default>
export const LazyUiModal: LazyComponent<typeof import("../app/components/ui/UiModal.vue").default>
export const LazyUiOfflineIndicator: LazyComponent<typeof import("../app/components/ui/UiOfflineIndicator.vue").default>
export const LazyUiPagination: LazyComponent<typeof import("../app/components/ui/UiPagination.vue").default>
export const LazyUiProgress: LazyComponent<typeof import("../app/components/ui/UiProgress.vue").default>
export const LazyUiRadio: LazyComponent<typeof import("../app/components/ui/UiRadio.vue").default>
export const LazyUiSelect: LazyComponent<typeof import("../app/components/ui/UiSelect.vue").default>
export const LazyUiSkeleton: LazyComponent<typeof import("../app/components/ui/UiSkeleton.vue").default>
export const LazyUiSpinner: LazyComponent<typeof import("../app/components/ui/UiSpinner.vue").default>
export const LazyUiSwitch: LazyComponent<typeof import("../app/components/ui/UiSwitch.vue").default>
export const LazyUiTabs: LazyComponent<typeof import("../app/components/ui/UiTabs.vue").default>
export const LazyUiTextarea: LazyComponent<typeof import("../app/components/ui/UiTextarea.vue").default>
export const LazyUiToast: LazyComponent<typeof import("../app/components/ui/UiToast.vue").default>
export const LazyUiTooltip: LazyComponent<typeof import("../app/components/ui/UiTooltip.vue").default>
export const LazyFormCheckbox: LazyComponent<typeof import("../app/components/form/FormCheckbox.vue").default>
export const LazyFormDatePicker: LazyComponent<typeof import("../app/components/form/FormDatePicker.vue").default>
export const LazyFormField: LazyComponent<typeof import("../app/components/form/FormField.vue").default>
export const LazyFormFileUpload: LazyComponent<typeof import("../app/components/form/FormFileUpload.vue").default>
export const LazyFormInput: LazyComponent<typeof import("../app/components/form/FormInput.vue").default>
export const LazyFormSelect: LazyComponent<typeof import("../app/components/form/FormSelect.vue").default>
export const LazyFormSwitch: LazyComponent<typeof import("../app/components/form/FormSwitch.vue").default>
export const LazyFormTextarea: LazyComponent<typeof import("../app/components/form/FormTextarea.vue").default>
export const LazyLanguageSwitcher: LazyComponent<typeof import("../app/components/layout/LanguageSwitcher.vue").default>
export const LazyPageHeader: LazyComponent<typeof import("../app/components/layout/PageHeader.vue").default>
export const LazySidebarItem: LazyComponent<typeof import("../app/components/layout/SidebarItem.vue").default>
export const LazyTheHeader: LazyComponent<typeof import("../app/components/layout/TheHeader.vue").default>
export const LazyTheSidebar: LazyComponent<typeof import("../app/components/layout/TheSidebar.vue").default>
export const LazyThemeToggle: LazyComponent<typeof import("../app/components/layout/ThemeToggle.vue").default>
export const LazyUserMenu: LazyComponent<typeof import("../app/components/layout/UserMenu.vue").default>
export const LazyDataTable: LazyComponent<typeof import("../app/components/data/DataTable.vue").default>
export const LazyDataTableActions: LazyComponent<typeof import("../app/components/data/DataTableActions.vue").default>
export const LazyAreaChart: LazyComponent<typeof import("../app/components/charts/AreaChart.vue").default>
export const LazyBarChart: LazyComponent<typeof import("../app/components/charts/BarChart.vue").default>
export const LazyDonutChart: LazyComponent<typeof import("../app/components/charts/DonutChart.vue").default>
export const LazyLineChart: LazyComponent<typeof import("../app/components/charts/LineChart.vue").default>
export const LazyPieChart: LazyComponent<typeof import("../app/components/charts/PieChart.vue").default>
export const LazyAIProviderStatus: LazyComponent<typeof import("../app/components/dashboard/AIProviderStatus.vue").default>
export const LazyLowStockAlerts: LazyComponent<typeof import("../app/components/dashboard/LowStockAlerts.vue").default>
export const LazyRecentConversations: LazyComponent<typeof import("../app/components/dashboard/RecentConversations.vue").default>
export const LazyRecentOrders: LazyComponent<typeof import("../app/components/dashboard/RecentOrders.vue").default>
export const LazyStatsCard: LazyComponent<typeof import("../app/components/dashboard/StatsCard.vue").default>
export const LazySystemHealth: LazyComponent<typeof import("../app/components/dashboard/SystemHealth.vue").default>
export const LazyConversationChat: LazyComponent<typeof import("../app/components/conversations/ConversationChat.vue").default>
export const LazyConversationFilters: LazyComponent<typeof import("../app/components/conversations/ConversationFilters.vue").default>
export const LazyConversationList: LazyComponent<typeof import("../app/components/conversations/ConversationList.vue").default>
export const LazyCustomerSidebar: LazyComponent<typeof import("../app/components/conversations/CustomerSidebar.vue").default>
export const LazyMessageBubble: LazyComponent<typeof import("../app/components/conversations/MessageBubble.vue").default>
export const LazyOrderFilters: LazyComponent<typeof import("../app/components/orders/OrderFilters.vue").default>
export const LazyOrderItemsTable: LazyComponent<typeof import("../app/components/orders/OrderItemsTable.vue").default>
export const LazyOrderList: LazyComponent<typeof import("../app/components/orders/OrderList.vue").default>
export const LazyOrderStatusBadge: LazyComponent<typeof import("../app/components/orders/OrderStatusBadge.vue").default>
export const LazyOrderSummary: LazyComponent<typeof import("../app/components/orders/OrderSummary.vue").default>
export const LazyOrderTimeline: LazyComponent<typeof import("../app/components/orders/OrderTimeline.vue").default>
export const LazyProductCard: LazyComponent<typeof import("../app/components/products/ProductCard.vue").default>
export const LazyProductFilters: LazyComponent<typeof import("../app/components/products/ProductFilters.vue").default>
export const LazyProductForm: LazyComponent<typeof import("../app/components/products/ProductForm.vue").default>
export const LazyProductImages: LazyComponent<typeof import("../app/components/products/ProductImages.vue").default>
export const LazyProductList: LazyComponent<typeof import("../app/components/products/ProductList.vue").default>
export const LazyProductVariants: LazyComponent<typeof import("../app/components/products/ProductVariants.vue").default>
export const LazyStockBadge: LazyComponent<typeof import("../app/components/products/StockBadge.vue").default>
export const LazyCustomerConversations: LazyComponent<typeof import("../app/components/customers/CustomerConversations.vue").default>
export const LazyCustomerFilters: LazyComponent<typeof import("../app/components/customers/CustomerFilters.vue").default>
export const LazyCustomerList: LazyComponent<typeof import("../app/components/customers/CustomerList.vue").default>
export const LazyCustomerOrders: LazyComponent<typeof import("../app/components/customers/CustomerOrders.vue").default>
export const LazyCustomerStats: LazyComponent<typeof import("../app/components/customers/CustomerStats.vue").default>
export const LazyKnowledgeForm: LazyComponent<typeof import("../app/components/settings/KnowledgeForm.vue").default>
export const LazyKnowledgeList: LazyComponent<typeof import("../app/components/settings/KnowledgeList.vue").default>
export const LazyPatternSection: LazyComponent<typeof import("../app/components/settings/PatternSection.vue").default>
export const LazySettingsBot: LazyComponent<typeof import("../app/components/settings/SettingsBot.vue").default>
export const LazySettingsCurrency: LazyComponent<typeof import("../app/components/settings/SettingsCurrency.vue").default>
export const LazySettingsNotifications: LazyComponent<typeof import("../app/components/settings/SettingsNotifications.vue").default>
export const LazySettingsShipping: LazyComponent<typeof import("../app/components/settings/SettingsShipping.vue").default>
export const LazySettingsStoreInfo: LazyComponent<typeof import("../app/components/settings/SettingsStoreInfo.vue").default>
export const LazyTemplateForm: LazyComponent<typeof import("../app/components/settings/TemplateForm.vue").default>
export const LazyTemplatesList: LazyComponent<typeof import("../app/components/settings/TemplatesList.vue").default>
export const LazyGlobalConfirmDialog: LazyComponent<typeof import("../app/components/GlobalConfirmDialog.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
